name: Build and Publish

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Run build.ps1 and publish.ps1 on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install PowerShell
        run: |
          brew install --cask powershell

      - name: Run build.ps1
        shell: pwsh
        run: |
          ./build.ps1 ${{ github.event_name == 'push' && format('-PreRelease "beta.{0}"', github.run_number) || '' }}

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          ./publish.ps1

      - name: Upload packages to release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: ./.dist/*.tgz

      - name: Upload packages to workflow run
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./.dist/*.tgz
          include-hidden-files: true